name: Read secrets from vault
on:
  push:
    branches: [ main ]

jobs:
  bash-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install vault-cli
        run: |
          sudo apt-get update && sudo apt-get install gpg wget 
          wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "wget done"
          gpg --no-default-keyring --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg --fingerprint
          echo "gpg done"
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          echo "echo is done"
          sudo apt-get update && sudo apt-get install vault
      - name: verifying vault
        run: vault status
      - name: Run docker-compose
        uses: hoverkraft-tech/compose-action@v2
        with:
          compose-file: "./vault-docker/docker-compose.yml"


